from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam
import numpy as np

class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer
        
        base_model = models.load_model('results/basic_model_30_epochs_timestamp_1771181659.keras')

        self._randomize_layers(base_model)
        
        base_model.trainable = True
        
    
        base_model.pop()


        self.model = Sequential([
            base_model,
            layers.Dense(64, activation='relu'),
            layers.Dropout(0.2),
            layers.Dense(categories_count, activation='softmax')
        ])
        pass
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=RMSprop(learning_rate=0.0008),
            loss='categorical_crossentropy',
            metrics=['accuracy'],
        )
        pass

    @staticmethod
    def _randomize_layers(model):
        # Your code goes here

        # you can write a function here to set the weights to a random value
        # use this function in _define_model to randomize the weights of your loaded model

        for layer in model.layers:
            weights = layer.get_weights()
            if weights: 
                new_weights = []
                for w in weights:
                    new_weights.append(np.random.normal(0, 0.05, w.shape)) #make similar shape but diffrent wieghts
                layer.set_weights(new_weights)
        pass
